import { useEffect, useState } from 'react';
import { Loader2, RefreshCw, Search, Check } from 'lucide-react';
import AdminLayout from '../../components/admin/AdminLayout';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';

const fmt=(d:string)=>new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'2-digit',month:'short',timeZone:'Asia/Dhaka'}).format(new Date(`${d}T00:00:00+06:00`));
export default function MealPreferencesManagement(){
 const {profile}=useAuth(); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [month,setMonth]=useState(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}); const [isDark,setIsDark]=useState(()=>localStorage.getItem('adminTheme')!=='light');
 useEffect(()=>{const id=setInterval(()=>setIsDark(localStorage.getItem('adminTheme')!=='light'),100);return()=>clearInterval(id)},[]); useEffect(()=>{if(profile)load()},[profile,month]);
 async function load(){try{setLoading(true);const hostelId=(profile as any).id;const start=`${month}-01`;const end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10);const {data,error}=await supabase.from('meal_preferences').select('id,meal_date,meal_time,preferred_item,member:members(name,email),meal:meals(day_menu_name,night_menu_name)').eq('hostel_id',hostelId).gte('meal_date',start).lte('meal_date',end).order('meal_date').order('meal_time');if(error)throw error;setRows((data||[]).map((r:any)=>({...r,member:Array.isArray(r.member)?r.member[0]:r.member,meal:Array.isArray(r.meal)?r.meal[0]:r.meal})));}catch(e:any){alert(e.message||'Could not load preferences.')}finally{setLoading(false)}}
 const filtered=rows.filter(r=>!search.trim()||r.member?.name?.toLowerCase().includes(search.toLowerCase())||r.member?.email?.toLowerCase().includes(search.toLowerCase())||r.preferred_item?.toLowerCase().includes(search.toLowerCase()));
 return <AdminLayout><div className="w-full max-w-7xl mx-auto"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4 mb-8"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-500">Planning</p><h1 className={`text-3xl sm:text-4xl font-extrabold mt-1 ${isDark?'text-white':'text-slate-900'}`}>Meal Preferences</h1><p className="text-sm mt-2 text-slate-500">See what every member wants to eat on each date and meal time.</p></div><div className="flex gap-2"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className={`px-4 py-2.5 rounded-xl border ${isDark?'bg-slate-900/60 border-white/10 text-white [color-scheme:dark]':'bg-white border-slate-200'}`}/><button onClick={load} className={`px-4 py-2.5 rounded-xl border ${isDark?'border-white/10 bg-white/5 text-slate-200':'border-slate-200 bg-white text-slate-700'}`}><RefreshCw size={16}/></button></div></div>
 <div className={`rounded-3xl border p-4 mb-5 ${isDark?'bg-slate-800/50 border-white/5':'bg-white border-slate-200'}`}><div className="relative"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search member or food item..." className={`w-full pl-11 pr-4 py-3 rounded-xl border outline-none focus:ring-2 focus:ring-indigo-500 ${isDark?'bg-slate-900/60 border-white/10 text-white':'bg-slate-50 border-slate-200'}`}/></div></div>
 <div className={`rounded-3xl border overflow-hidden ${isDark?'bg-slate-800/50 border-white/5':'bg-white border-slate-200 shadow-sm'}`}>{loading?<div className="p-12 flex justify-center"><Loader2 className="animate-spin text-indigo-500"/></div>:filtered.length===0?<div className="p-12 text-center text-sm text-slate-500">No preferences found.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className={isDark?'bg-slate-900/50':'bg-slate-50'}><th className="px-6 py-4 text-xs uppercase tracking-widest text-slate-500">Date</th><th className="px-6 py-4 text-xs uppercase tracking-widest text-slate-500">Time</th><th className="px-6 py-4 text-xs uppercase tracking-widest text-slate-500">Member</th><th className="px-6 py-4 text-xs uppercase tracking-widest text-slate-500">Preferred Item</th></tr></thead><tbody className={`divide-y ${isDark?'divide-white/5':'divide-slate-100'}`}>{filtered.map(r=><tr key={r.id}><td className="px-6 py-4 text-sm text-slate-400">{fmt(r.meal_date)}</td><td className="px-6 py-4 text-sm font-semibold text-slate-400">{r.meal_time==='day'?'Day / Lunch':'Night / Dinner'}</td><td className={`px-6 py-4 text-sm font-semibold ${isDark?'text-white':'text-slate-900'}`}>{r.member?.name}<div className="text-xs text-slate-500 font-normal">{r.member?.email}</div></td><td className={`px-6 py-4 text-sm ${isDark?'text-slate-300':'text-slate-700'}`}><span className="inline-flex items-center gap-2"><Check size={15} className="text-emerald-500"/>{r.preferred_item}</span></td></tr>)}</tbody></table></div>}</div></div></AdminLayout>
}
